import { useEffect, useState } from 'react'
import { GitBranch, CheckCircle2, XCircle, Sparkles, Trophy } from 'lucide-react'
import { Button, Spinner, Pill, Textarea } from '../ui'
import { generatePractice, checkAnswer } from '../../lib/practice'
import { aiEnabled } from '../../lib/ai'
import { cx } from '../../lib/utils'

/**
 * "Branch out": extra practice after a weak checkpoint (< 60).
 * Generates 4 items (AI or curated bank), checks locally, awards 40 pts and re-scores the lesson on completion.
 */
export default function PracticeBranch({ lesson, course, studentName, baseScore, onFinish }) {
  const [items, setItems] = useState(null)
  const [answers, setAnswers] = useState({})
  const [checks, setChecks] = useState({})
  const [finished, setFinished] = useState(null)

  useEffect(() => {
    let alive = true
    ;(async () => {
      if (!aiEnabled) await new Promise((r) => setTimeout(r, 700))
      const topics = lesson.topics.map((t) => ({ ...t, score: baseScore }))
      const out = await generatePractice({ lesson, course, topics, studentName, count: 4 })
      if (alive) setItems(out)
    })()
    return () => { alive = false }
  }, [lesson, course, studentName, baseScore])

  const check = (item) => setChecks((c) => ({ ...c, [item.id]: checkAnswer(item, answers[item.id]) }))
  const answered = items ? items.filter((it) => checks[it.id] !== undefined).length : 0
  const correct = items ? items.filter((it) => checks[it.id] === true).length : 0

  const finish = () => {
    const pct = Math.round((correct / items.length) * 100)
    const newScore = Math.max(baseScore, Math.min(85, Math.round(baseScore * 0.4 + pct * 0.6)))
    setFinished({ pct, newScore })
    onFinish({ pct, newScore })
  }

  return (
    <div className="card p-6 border-2 border-dashed border-mango-300 bg-[linear-gradient(180deg,#FFF4E5_0%,#ffffff_120px)]" id="branch">
      <div className="flex flex-wrap items-start justify-between gap-3 mb-4">
        <div className="flex items-start gap-3">
          <div className="w-11 h-11 rounded-2xl bg-white border border-mango-200 text-mango flex items-center justify-center shrink-0"><GitBranch size={20} /></div>
          <div>
            <div className="font-hand text-mango text-xl leading-none mb-1">branch out</div>
            <h3 className="text-lg font-extrabold text-charcoal">Extra practice · {lesson.topics[0].name}</h3>
            <p className="text-sm text-charcoal-400 mt-1 max-w-xl">Your checkpoint came in at {baseScore}%. Four tailored questions — finish them to earn 40 points and raise this checkpoint’s score.</p>
          </div>
        </div>
        <Pill tone="mango" icon={Sparkles}>{aiEnabled ? 'Generated by BOLT' : 'Curated practice'}</Pill>
      </div>

      {!items && <div className="flex items-center gap-3 text-sm text-charcoal-400 py-6"><Spinner className="w-5 h-5" /> Building your practice branch…</div>}

      {items && (
        <div className="grid md:grid-cols-2 gap-4">
          {items.map((it, i) => {
            const res = checks[it.id]
            return (
              <div key={it.id} className={cx('rounded-2xl border bg-white p-4 space-y-3', res === true ? 'border-success/40' : res === false ? 'border-danger/40' : 'border-charcoal-100')}>
                <div className="flex items-center justify-between text-[11px]">
                  <span className="font-semibold uppercase tracking-wide text-charcoal-400">Q{i + 1} · {it.context || it.topic}</span>
                  <span className="text-charcoal-300">{'●'.repeat(it.difficulty || 1)}{'○'.repeat(3 - (it.difficulty || 1))}</span>
                </div>
                <p className="text-sm text-charcoal font-medium leading-snug">{it.prompt}</p>
                {it.type === 'choice' && (
                  <div className="space-y-1.5">
                    {it.options?.map((o) => (
                      <button key={o} type="button" disabled={res !== undefined} onClick={() => setAnswers((a) => ({ ...a, [it.id]: o }))} className={cx('w-full text-left rounded-xl border px-3 py-2 text-sm transition-all', answers[it.id] === o ? 'border-mango bg-mango-50' : 'border-charcoal-100 hover:border-charcoal-300', res !== undefined && o === String(it.answer) && 'border-success bg-success-soft')}>{o}</button>
                    ))}
                  </div>
                )}
                {it.type === 'numeric' && <input value={answers[it.id] ?? ''} disabled={res !== undefined} onChange={(e) => setAnswers((a) => ({ ...a, [it.id]: e.target.value }))} inputMode="decimal" placeholder="number" className="w-40 rounded-xl border border-charcoal-200 px-3 py-2 text-sm font-bold focus:outline-none focus:border-mango" />}
                {it.type === 'short' && <Textarea rows={2} value={answers[it.id] ?? ''} disabled={res !== undefined} onChange={(e) => setAnswers((a) => ({ ...a, [it.id]: e.target.value }))} placeholder="At least 8 words…" />}
                {res === undefined ? (
                  <Button size="sm" variant="dark" onClick={() => check(it)} disabled={answers[it.id] == null || answers[it.id] === ''}>Check</Button>
                ) : (
                  <div className={cx('flex gap-2 text-xs rounded-xl p-3', res ? 'bg-success-soft text-charcoal' : 'bg-danger-soft text-charcoal')}>
                    {res ? <CheckCircle2 size={15} className="text-success shrink-0 mt-0.5" /> : <XCircle size={15} className="text-danger shrink-0 mt-0.5" />}
                    <span><span className="font-bold">{res ? 'Correct.' : `Answer: ${it.answer}.`}</span> {it.explanation}</span>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}

      {items && (
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
          <div className="text-sm text-charcoal-500">{answered}/{items.length} checked · {correct} correct</div>
          {finished ? (
            <div className="flex items-center gap-2 rounded-full bg-success-soft text-success px-4 py-2 text-sm font-bold fade-up"><Trophy size={16} /> +40 points · checkpoint re-scored to {finished.newScore}%</div>
          ) : (
            <Button onClick={finish} disabled={answered < items.length}><GitBranch size={16} /> Finish branch · +40 pts</Button>
          )}
        </div>
      )}
    </div>
  )
}
